/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Election;

import Login.AdminMenu;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author BlackDragon
 */
public class AddElection extends javax.swing.JFrame {

    /**
     * Creates new form AddElection
     */
    public AddElection() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2 - getHeight()/2);
        setTitle("Add Election");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new com.github.lgooddatepicker.components.DateTimePicker();
        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Dscrip = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        stop = new com.github.lgooddatepicker.components.DateTimePicker();
        AddElectionBtn = new javax.swing.JButton();
        Warn = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(405, 380));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Add Election");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 260, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Description:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        Dscrip.setColumns(20);
        Dscrip.setRows(5);
        jScrollPane1.setViewportView(Dscrip);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 260, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Start Time:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Stop Time:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        getContentPane().add(stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        AddElectionBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddElectionBtn.setText("ADD");
        AddElectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddElectionBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddElectionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 103, 39));

        Warn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Warn.setForeground(new java.awt.Color(255, 0, 0));
        Warn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Warn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 255, 416, -1));

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Election/g1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void AddElectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddElectionBtnActionPerformed
        // TODO add your handling code here:
        if (name.getText().trim().isEmpty() || Dscrip.getText().trim().isEmpty()
                || start.getDateTimeStrict() == null || stop.getDateTimeStrict() == null) {
            Warn.setText("Any Field can't be Blank");
            
        } else if (!stop.getDateTimeStrict().isAfter(start.getDateTimeStrict())) {
            Warn.setText("Stop time must be after start time");
        } else {
            Warn.setText("");
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/votingsystem", "root", "");
                String quary = "INSERT INTO `elections`( `Name`, `Description`, `StartTime`, `StopTime`)\n"+
                        " VALUES (?,?,?,?);";
                PreparedStatement pst = con.prepareStatement(quary);
                pst.setString(1,name.getText());
                pst.setString(2,Dscrip.getText());
                pst.setString(3, start.getDateTimeStrict().toString());
                pst.setString(4, stop.getDateTimeStrict().toString());
                int count = pst.executeUpdate();
                if(count ==1){
                    JOptionPane.showMessageDialog(rootPane, "Election Added");
                    
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Somthing wrong");
                }
                

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
    }//GEN-LAST:event_AddElectionBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        AdminMenu menue = new AdminMenu();
        menue.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddElection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddElection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddElection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddElection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddElection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddElectionBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextArea Dscrip;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Warn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private com.github.lgooddatepicker.components.DateTimePicker start;
    private com.github.lgooddatepicker.components.DateTimePicker stop;
    // End of variables declaration//GEN-END:variables
}
