/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Election;

import Login.AdminMenu;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JLabel;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;

/**
 *
 * @author BlackDragon
 */
public class AddSymbol extends javax.swing.JFrame {

    /**
     * Creates new form AddSymbol
     */
    File selectedFile;
    public AddSymbol() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        setTitle("Add Symbol");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        ImageName = new javax.swing.JTextField();
        imageArea = new javax.swing.JLabel();
        BrowseImg = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        warnings = new javax.swing.JLabel();
        Warning = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 40, -1, -1));
        getContentPane().add(ImageName, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 44, 326, -1));

        imageArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        imageArea.setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().add(imageArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 84, 250, 250));

        BrowseImg.setText("Browse Image");
        BrowseImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseImgActionPerformed(evt);
            }
        });
        getContentPane().add(BrowseImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        warnings.setForeground(new java.awt.Color(255, 0, 0));
        warnings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(warnings, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 356, -1, -1));

        Warning.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Warning.setForeground(new java.awt.Color(255, 0, 0));
        Warning.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Election/g2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrowseImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseImgActionPerformed
        // TODO add your handling code here:
        JFileChooser choose = new JFileChooser();
        choose.setCurrentDirectory(new File(System.getProperty("user.home")));
        choose.setDialogTitle("Choose Election symbol image");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG JPG GIF and JPEG", "png", "gif","jpeg","jpg");
        choose.addChoosableFileFilter(filter);
        int result = choose.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = choose.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();
            String name = ImageName.getText();
            ImageIcon icon = new ImageIcon(filePath);
            Image image = icon.getImage().getScaledInstance(250, 250, Image.SCALE_SMOOTH);
            icon = new ImageIcon(image);
            imageArea.setIcon(icon);
            
        }
        
    }//GEN-LAST:event_BrowseImgActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        if(selectedFile == null){
            Warning.setText("Please Select an Image");
        }
        else if(ImageName.getText().isEmpty()){
            Warning.setText("Please Enter Symbol Name");
        }
        else{
            if (selectedFile.length() <= 507200) {
                try {
                    // Connect to the database
//                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/votingsystem", "root", "");

                    // Insert the image into the database
                    PreparedStatement pst = con.prepareStatement("INSERT INTO `symbols`( `name`, `path`) VALUES (?,?);");
                    pst.setString(1, ImageName.getText());
                    pst.setString(2, "/images/" + selectedFile.getName());
                    int count = pst.executeUpdate();
                    if(count ==1){
                        JOptionPane.showMessageDialog(rootPane, "Uploaded sucessfully");
                        

                        // Save the image to the project folder
                        File file = new File("");
                        String projectPath = file.getAbsolutePath();
                        File destFile = new File(projectPath+"/images/" + selectedFile.getName());
                        System.out.println(selectedFile.toPath().toString() +"\t"+ destFile.toPath());
                        Files.copy(selectedFile.toPath(), destFile.toPath());
                        selectedFile = null;
                        imageArea.setIcon(null);
                    
                    }
                    else{
                         JOptionPane.showMessageDialog(rootPane, "Somthing wrong");
                    }   

                    
//                    
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error uploading image: " + ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "File size should be less than 500 KB");
            }
        }
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        AdminMenu ad = new AdminMenu();
        ad.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSymbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSymbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSymbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSymbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSymbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton BrowseImg;
    private javax.swing.JTextField ImageName;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel Warning;
    private javax.swing.JLabel imageArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel warnings;
    // End of variables declaration//GEN-END:variables
}
