/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Election;

import Login.AdminMenu;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author BlackDragon
 */
public class AddVoter extends javax.swing.JFrame {

    /**
     * Creates new form AddVoter
     */
    public AddVoter() {
        initComponents();
        setTitle("Add Voter");
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2 - getHeight()/2);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/votingsystem", "root", "");
            String quary = "SELECT `Name`, `StopTime` FROM `elections`";
            PreparedStatement pst = con.prepareStatement(quary);
            ResultSet res = pst.executeQuery();
            LocalDateTime now = LocalDateTime.now();
            
            elections.removeAllItems();
            while(res.next()){
                if(now.isBefore(LocalDateTime.parse(res.getString(2)))){
                    elections.addItem(res.getString(1));
                }
               
            }
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        elections = new javax.swing.JComboBox<>();
        name = new javax.swing.JTextField();
        nid = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Warn = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("COUTURE", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Voter");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 25, 394, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NID No.:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Usename:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Election:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 220, -1, -1));

        elections.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NULL", " " }));
        elections.setSelectedIndex(-1);
        elections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electionsActionPerformed(evt);
            }
        });
        getContentPane().add(elections, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 220, 255, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 60, 255, -1));
        getContentPane().add(nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 100, 255, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 140, 255, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 180, 255, -1));

        AddBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddBtn.setText("ADD");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 305, 86, 57));

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 317, -1, -1));

        Warn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Warn.setForeground(new java.awt.Color(255, 0, 0));
        Warn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Warn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 259, 388, 28));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Election/g1.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void electionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_electionsActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        AdminMenu menue = new AdminMenu();
        menue.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BackActionPerformed
String makePassword(int n)
 {
 
  // chose a Character random from this String
  String AlphaNumericString = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
         + "0123456789"
         + "abcdefghijklmnopqrstuvxyz";
 
  // create StringBuffer size of AlphaNumericString
  StringBuilder sb = new StringBuilder(n);
 
  for (int i = 0; i < n; i++) {
 
   // generate a random number between
   // 0 to AlphaNumericString variable length
   int index
    = (int)(AlphaNumericString.length()
      * Math.random());
 
   // add Character one by one in end of sb
   sb.append(AlphaNumericString
      .charAt(index));
  }
 
  return sb.toString();
 }
    public static boolean validate10DigitNumber(String num) {
    return num.matches("\\d{10}");
}
public static boolean validateEmailAddress(String email) {
    int atIndex = email.indexOf("@");
    int dotIndex = email.lastIndexOf(".");

    if (atIndex < 1 || dotIndex < atIndex + 2 || dotIndex + 2 >= email.length()) {
        return false;
    }

    for (int i = 0; i < email.length(); i++) {
        char c = email.charAt(i);
        if (i == 0 || i == atIndex - 1 || i == atIndex + 1 || i == email.length() - 1) {
            if (!Character.isLetterOrDigit(c)) {
                return false;
            }
        } else {
            if (!Character.isLetterOrDigit(c) && c != '.' && c != '_' && c != '-' && c != '@') {
                return false;
            }
        }
    }

    return true;
}



    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        if(name.getText().trim().isEmpty() || nid.getText().trim().isEmpty()
                || email.getText().trim().isEmpty()|| username.getText().trim().isEmpty()){
            Warn.setText("Every Field Must be Filled");
        }
        else if(!validate10DigitNumber(nid.getText())){
            Warn.setText("Enter Valid 10 digit NID number");
        }
        else if(!validateEmailAddress(email.getText())){
            Warn.setText("Enter Valid Valid email Adress");
        }
        else{
            try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/votingsystem", "root","");
            String quary = "SELECT * FROM `voterinfo` WHERE `username` = '"+username.getText()+"';";            
            PreparedStatement pst = con.prepareStatement(quary);
            ResultSet res = pst.executeQuery();
            if(!res.next()){
                quary = "INSERT INTO `voterinfo`( `name`, `nid`, `email`, `username`, `pass`, `election`) VALUES (?,?,?,?,?,?);";
                pst = con.prepareStatement(quary);
                pst.setString(1, name.getText());
                pst.setString(2, nid.getText());
                pst.setString(3, email.getText());
                pst.setString(4, username.getText());
                String pass = makePassword(10);
                pst.setString(5, pass);
                pst.setString(6, elections.getSelectedItem().toString());
                int count1 = pst.executeUpdate();
                quary = "INSERT INTO `users`(`username`, `pass`, `isAdmin`) VALUES (?,?,0)";
                pst = con.prepareStatement(quary);
                pst.setString(1,username.getText());
                pst.setString(2,pass);
                int count2 = pst.executeUpdate();
                
                if(count1==1 && count2 ==1){
                    JOptionPane.showMessageDialog(rootPane, "Voter Added\n"
                            + "Username: "+ username.getText()+"\n"
                                    + "Password: "+pass);
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "An Error");
                }
            }
            else{
                Warn.setText("Username aleardy exist");
            }
            
            
           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        }
        
    }//GEN-LAST:event_AddBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVoter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton Back;
    private javax.swing.JLabel Warn;
    private javax.swing.JComboBox<String> elections;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nid;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
