/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author BlackDragon
 */
public class Vote extends javax.swing.JFrame {

    /**
     * Creates new form Vote
     */
    String usernameme,password,electionName;
    int count = 1;
    int candidatelist[],symbol_id,selectedCndidID;
    String symbol_path;
    public Vote() {
        initComponents();
    }
    public Vote(String user, String pass){
        initComponents();
        setTitle("Vote");
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        usernameme=user;
        password= pass;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/votingsystem", "root","");
            String quary = "SELECT `election` FROM `voterinfo` \n" +
                   
                    "WHERE username = '"+user+"' and pass = '"+pass+"'";
            PreparedStatement pst = con.prepareStatement(quary);
            ResultSet res = pst.executeQuery();
            if(res.next()){
                ElectionTitle.setText(res.getString(1));
                electionName = res.getString(1);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "voter data not found in database");
            }
            quary = "SELECT `candidate_ID`, `Name`,  `symbol_name`, `symbol_path` FROM `candidate` \n" +
                    "WHERE election_name = \""+electionName+"\" ;";
            pst = con.prepareStatement(quary);
            res = pst.executeQuery();
            Candidates.removeAllItems();
            candidatelist = new int[15];
            
            int count=0;
            while(res.next()){
                Candidates.addItem(res.getString(2)+" - "+res.getString(3));
                candidatelist[count++]=res.getInt(1);
            }
            
            
           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ElectionTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Candidates = new javax.swing.JComboBox<>();
        imageArea = new javax.swing.JLabel();
        voteBtn = new javax.swing.JButton();
        Logoutbtn = new javax.swing.JButton();
        warning = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ElectionTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ElectionTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ElectionTitle.setText("Election name");
        ElectionTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ElectionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 660, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText(" Select your preferred candidate");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        Candidates.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Candidates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidatesActionPerformed(evt);
            }
        });
        getContentPane().add(Candidates, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 401, -1));

        imageArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(imageArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 200, 200));

        voteBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        voteBtn.setText("Confirm Vote");
        voteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(voteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, 44));

        Logoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logoutbtn.setText("Logout");
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 110, 40));

        warning.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 0, 102));
        getContentPane().add(warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 392, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/vote.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_LogoutbtnActionPerformed

    private void CandidatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidatesActionPerformed
        // TODO add your handling code here:
        if(Candidates.getSelectedIndex()!=-1){
        int index = Candidates.getSelectedIndex();
        selectedCndidID = candidatelist[index];
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/votingsystem", "root","");
            String quary = "SELECT  `symbol_id`, `symbol_path` FROM `candidate` \n" +
                    "WHERE candidate_ID = "+selectedCndidID+" ;";
            PreparedStatement pst = con.prepareStatement(quary);
            ResultSet res = pst.executeQuery();
            while(res.next()){
                   String Path = res.getString(2);
                   symbol_id=res.getInt(1);
                   symbol_path = Path;
                   File file = new File("");
                   String projectPath = file.getAbsolutePath();

                   ImageIcon icon = new ImageIcon(projectPath+Path);
                   Image image = icon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
                   icon = new ImageIcon(image);
                   imageArea.setIcon(icon);

               }
               con.close();
            
            
           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        }
        
        
    }//GEN-LAST:event_CandidatesActionPerformed

    private void voteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteBtnActionPerformed
        // TODO add your handling code here:
        if(count!=1){
            warning.setText("You have already Voted");
        }
        else if( selectedCndidID==0){
            warning.setText("Please choose your preferred candidate");
        }
        else{
            warning.setText("");
            try{
                 Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/votingsystem", "root","");
            String quary = "SELECT `candidate_ID`,  `Vote` FROM `candidate` WHERE candidate_ID = "+selectedCndidID+";";
            PreparedStatement pst = con.prepareStatement(quary);
            ResultSet res = pst.executeQuery();
            if(res.next()){
                int preVote = res.getInt(2);
                   preVote++;
                   quary = "UPDATE `candidate` SET `Vote`= "+preVote+" WHERE candidate_ID = "+selectedCndidID+";";
                   pst = con.prepareStatement(quary);
                   int c1 = pst.executeUpdate();
                   quary = "update  `users` set isEnbaled=0 WHERE `username` = '"+usernameme+"' and `pass` = '"+password+"';;";
                   pst = con.prepareStatement(quary);
                   int c2 = pst.executeUpdate();
                   if(c1==1 && c2==1){
                       JOptionPane.showMessageDialog(rootPane, "You have sucessfully Voted your preferred candidate");
                   }
                   else{
                       JOptionPane.showMessageDialog(rootPane, "An Error Occured");
                   }

               }
               con.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
        
    }//GEN-LAST:event_voteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Candidates;
    private javax.swing.JLabel ElectionTitle;
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JLabel imageArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton voteBtn;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
